# Generated by Django 5.2.7 on 2025-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_bill_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('military_certificate_date', models.DateField()),
                ('package_count', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('permit_withdrawal_date', models.DateField()),
                ('payment_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customs_certificate', models.CharField(max_length=100)),
                ('contract_status', models.CharField(max_length=255)),
                ('shipment_submission_date', models.DateField()),
                ('release_permit_date', models.DateField()),
                ('disbursement_date', models.DateField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('ground_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
