# Generated by Django 5.2.7 on 2025-11-09 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_supplier', models.BooleanField(default=False, help_text='True if supplier, False if customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg', max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, help_text='Volume in cubic meters', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('type', models.CharField(choices=[('main', 'Main'), ('temp', 'Temporary')], default='main', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipment_type', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_customer', models.ForeignKey(blank=True, help_text='Destination customer (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_destination', to='api.customer')),
                ('origin_customer', models.ForeignKey(blank=True, help_text='Origin customer/supplier (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_origin', to='api.customer')),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_destination', to='api.warehouse')),
                ('origin_warehouse', models.ForeignKey(blank=True, help_text='Origin warehouse (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_origin', to='api.warehouse')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (pcs, kg, boxes, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='api.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.shipment')),
            ],
            options={
                'db_table': 'shipment_items',
                'ordering': ['-created_at'],
                'unique_together': {('shipment', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_quantity', models.DecimalField(decimal_places=2, help_text='Quantity linked from IN to OUT shipment', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_shipment', models.ForeignKey(help_text='Source IN shipment', limit_choices_to={'shipment_type': 'IN'}, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='api.shipment')),
                ('out_shipment', models.ForeignKey(help_text='Destination OUT shipment', limit_choices_to={'shipment_type': 'OUT'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_links', to='api.shipment')),
            ],
            options={
                'db_table': 'shipment_links',
                'ordering': ['-created_at'],
                'unique_together': {('in_shipment', 'out_shipment')},
            },
        ),
    ]
