# Generated by Django 5.2.7 on 2025-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipments',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='military_certificate_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='permit_withdrawal_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='release_permit_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='shipment_submission_date',
        ),
        migrations.AddField(
            model_name='shipments',
            name='bill_number',
            field=models.CharField(blank=True, help_text='رقم البوليصة', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='arrival_date',
            field=models.DateField(help_text='تاريخ الوصول'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='company_name',
            field=models.CharField(help_text='اسم الشركة', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='contract_status',
            field=models.CharField(help_text='الحالة', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='customs_certificate',
            field=models.CharField(help_text='الشهادة الجمركية', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='destination',
            field=models.CharField(help_text='الجهة', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='disbursement_date',
            field=models.DateField(blank=True, help_text='تاريخ الصرف (اختياري)', null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='ground_fees',
            field=models.DecimalField(decimal_places=2, help_text='رسوم الأرضية', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='package_count',
            field=models.PositiveIntegerField(help_text='عدد الطرود'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='payment_fees',
            field=models.DecimalField(decimal_places=2, help_text='رسوم الدفع', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='receiver_name',
            field=models.CharField(help_text='المستلم', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='sub_bill_number',
            field=models.CharField(help_text='رقم البوليصة الفرعية', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='الوزن', max_digits=10),
        ),
    ]
