# Generated by Django 5.2.7 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shipments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='bill_number',
            field=models.CharField(default='', help_text='رقم البوليصة', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
