# Generated by Django 5.2.7 on 2025-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shipments_bill_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipment',
            new_name='AdvancedShipment',
        ),
        migrations.RenameModel(
            old_name='ShipmentItem',
            new_name='AdvancedShipmentItem',
        ),
        migrations.RenameModel(
            old_name='ShipmentLink',
            new_name='AdvancedShipmentLink',
        ),
        migrations.AlterModelTable(
            name='advancedshipment',
            table='advanced_shipments',
        ),
        migrations.AlterModelTable(
            name='advancedshipmentitem',
            table='advanced_shipment_items',
        ),
        migrations.AlterModelTable(
            name='advancedshipmentlink',
            table='advanced_shipment_links',
        ),
        migrations.AlterModelTable(
            name='shipments',
            table='shipments',
        ),
        migrations.CreateModel(
            name='InShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='رقم البوليصة', max_length=100)),
                ('arrival_date', models.DateField(help_text='تاريخ الوصول')),
                ('sub_bill_number', models.CharField(help_text='رقم البوليصة الفرعية', max_length=100)),
                ('company_name', models.CharField(help_text='اسم الشركة', max_length=255)),
                ('package_count', models.PositiveIntegerField(help_text='عدد الطرود')),
                ('weight', models.DecimalField(decimal_places=2, help_text='الوزن', max_digits=10)),
                ('destination', models.CharField(help_text='الجهة', max_length=255)),
                ('payment_fees', models.DecimalField(decimal_places=2, help_text='رسوم الدفع', max_digits=10)),
                ('customs_certificate', models.CharField(help_text='الشهادة الجمركية', max_length=100)),
                ('contract_status', models.CharField(help_text='الحالة', max_length=255)),
                ('disbursement_date', models.DateField(blank=True, help_text='تاريخ الصرف (اختياري)', null=True)),
                ('receiver_name', models.CharField(help_text='المستلم', max_length=255)),
                ('ground_fees', models.DecimalField(decimal_places=2, help_text='رسوم الأرضية', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbound Shipment',
                'verbose_name_plural': 'Inbound Shipments',
                'db_table': 'in_shipments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('bill_number',), name='unique_in_shipment_bill_number')],
            },
        ),
        migrations.CreateModel(
            name='OutShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='رقم البوليصة', max_length=100)),
                ('arrival_date', models.DateField(help_text='تاريخ الوصول')),
                ('sub_bill_number', models.CharField(help_text='رقم البوليصة الفرعية', max_length=100)),
                ('company_name', models.CharField(help_text='اسم الشركة', max_length=255)),
                ('package_count', models.PositiveIntegerField(help_text='عدد الطرود')),
                ('weight', models.DecimalField(decimal_places=2, help_text='الوزن', max_digits=10)),
                ('destination', models.CharField(help_text='الجهة', max_length=255)),
                ('payment_fees', models.DecimalField(decimal_places=2, help_text='رسوم الدفع', max_digits=10)),
                ('customs_certificate', models.CharField(help_text='الشهادة الجمركية', max_length=100)),
                ('contract_status', models.CharField(help_text='الحالة', max_length=255)),
                ('disbursement_date', models.DateField(blank=True, help_text='تاريخ الصرف (اختياري)', null=True)),
                ('receiver_name', models.CharField(help_text='المستلم', max_length=255)),
                ('ground_fees', models.DecimalField(decimal_places=2, help_text='رسوم الأرضية', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbound Shipment',
                'verbose_name_plural': 'Outbound Shipments',
                'db_table': 'out_shipments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('bill_number',), name='unique_out_shipment_bill_number')],
            },
        ),
    ]
