# Generated by Django 5.2.7 on 2025-11-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inshipment',
            name='sub_bill_number',
            field=models.CharField(help_text='رقم البوليصة الفرعية', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='outshipment',
            name='sub_bill_number',
            field=models.CharField(help_text='رقم البوليصة الفرعية', max_length=100, unique=True),
        ),
    ]
