# Generated by Django 5.2.7 on 2025-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_inshipment_sub_bill_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outshipment',
            name='in_shipment',
        ),
        migrations.AddField(
            model_name='outshipment',
            name='in_shipments',
            field=models.ManyToManyField(help_text='Inbound shipments associated with this outbound record', related_name='out_shipments', to='api.inshipment'),
        ),
    ]
