# Generated by Django 5.2.7 on 2025-11-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_outshipment_in_shipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outshipment',
            name='in_shipments',
        ),
        migrations.AddField(
            model_name='inshipment',
            name='exported_count',
            field=models.PositiveIntegerField(default=0, help_text='عدد الطرود المُصدَّرة حتى الآن'),
        ),
        migrations.AddField(
            model_name='outshipment',
            name='in_shipment',
            field=models.ForeignKey(default='', help_text='الشحنة الواردة المرتبطة بهذه العملية', on_delete=django.db.models.deletion.PROTECT, related_name='out_shipments', to='api.inshipment'),
            preserve_default=False,
        ),
    ]
